name: Sync Articles from Super.so

on:
  schedule:
    # Roda todos os dias à meia-noite
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite execução manual

jobs:
  sync-articles:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Sync articles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Instala as dependências necessárias
          npm install puppeteer
          
          # Executa o script de sincronização
          node scripts/sync-articles.js
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          git add src/data/articles.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualiza artigos do Super.so" && git push) 